// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAabnyeMgIHY6aqWRukyz3zM9HYvT2ZUR0',
    appId: '1:791463957566:web:410827202f5cd7472e6d6f',
    messagingSenderId: '791463957566',
    projectId: 'atlas-news-app',
    authDomain: 'atlas-news-app.firebaseapp.com',
    storageBucket: 'atlas-news-app.appspot.com',
    measurementId: 'G-B31SE0P32G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgvLAU0qmUP5fQScYHuGhnS8izN2Rygt0',
    appId: '1:791463957566:android:4e87f33f2158309c2e6d6f',
    messagingSenderId: '791463957566',
    projectId: 'atlas-news-app',
    storageBucket: 'atlas-news-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqNCjlDbXaTvsBnIpBemFjUi14klfbGW8',
    appId: '1:791463957566:ios:2a2008deb16954f32e6d6f',
    messagingSenderId: '791463957566',
    projectId: 'atlas-news-app',
    storageBucket: 'atlas-news-app.appspot.com',
    iosBundleId: 'com.example.atlasNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqNCjlDbXaTvsBnIpBemFjUi14klfbGW8',
    appId: '1:791463957566:ios:67460457a7dd35012e6d6f',
    messagingSenderId: '791463957566',
    projectId: 'atlas-news-app',
    storageBucket: 'atlas-news-app.appspot.com',
    iosBundleId: 'com.example.atlasNewsApp.RunnerTests',
  );
}
